### PR TITLE
Rework to ES6

### PR DESCRIPTION
**Pull request by mudrz**
A couple of changes and notes
- Reworked the whole package to ES6
- Changed scripts `server` -> `start` per conventions
- Simplified `Icon.jsx`
- Moved code from wells to `Code` component. Code can be highlighted (`prismjs` has `jsx` support)
- `yarn`>`npm` even if it is only for `yarn.lock`
- you should consider moving the application to `create-react-app` template, the current build setup does not make for a good development experience
- I haven't moved the current structure to a hoc referencing sprites and grid size, but it is a good idea

### CODE REVIEW

**Comment by chad-autry** [comment]
- Reworked the whole package to ES6
    Yep, that looks good
- Changed scripts server -> start per conventions
   Yeah, my own idiosyncrasy that I've just ignored the automated warnings on
- Simplified Icon.jsx
    The mechanical changes look good, in particular spreading ...rest onto the parent svg seems better than the direction I had in the back of my mind (adding a particular attribute to spread)
- Moved code from wells to Code component. Code can be highlighted (prismjs has jsx support)
  Cool, I wasn't aware of the code block
- yarn>npm even if it is only for yarn.lock
   I'd prefer to upgrade to npm 5.0 with package-lock.json
- you should consider moving the application to create-react-app template, the current build setup does not make for a good development experience
  Nope, I've glanced at create-react-app and not a fan of having everything hidden like that. 
- I haven't moved the current structure to a hoc referencing sprites and grid size, but it is a good idea
  Yeah, definitely think an optional hoc would be good for grid size. I think sprite sheet reference needs to be considered in relation to webpack tree shaking/trimming

I'm not a huge fan of the massive white space changes, I used 4 space indentation on purpose.

I don't like the way longer elements were split across multiple lines. Particularly the trailing leading element name (for singe char elements like '<g' and '<i') and the trailing '>'. As a direct example I think <i className={this.state.menuCollapsed ? 'fa fa-chevron-right':'fa fa-chevron-down'}></i> should just be left alone. 

I was lazy and didn't run it myself (and needed to add some in), but the removed /* jshint ignore:start */ and /* jshint ignore:end */ comments will cause jshint to break on jsx when run

**Comment by mudrz** [comment]
create-react-app has `yarn eject` if you want to see all underlying configurations (has the downside that it can't be automatically updated later), but even without it webpack-hot-module replacement is very handy

The split is caused by https://github.com/prettier/prettier for supposedly easier readability (I am using https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

It sometimes creates such new line splits but overall makes development so much easier by not worrying about formatting. How do you format the files?

I am not familiar with `jshint`, have you checked eslint? It has proper jsx linting support and is really easy to setup https://github.com/facebookincubator/create-react-app/tree/master/packages/eslint-config-react-app - this shows how to set it up extending the linting defaults of create-react-app

**Comment by chad-autry** [comment]
I mostly edit code straight through github or on gcloud console. Ain't got no time to be messing with ides =P

With the link though, I'm not opposed to adding in prettier with a pre-commit hook to enforce a consistent style. That can be left for a later commit.

On JSHint vs ESLint, I don't recall why I went with JSHint, but I think it was working with Angular at the time so jsx wasn't a priority. Switching now for jsx support isn't a bad idea, again can be left for a later commit.

I'll take a further look, later on and get things merged in. I'll leave out the migration to yarn, and will again leave the npm upgrade to a later commit.

**Review by chad-autry — CHANGES_REQUESTED** [review]
The code block doesn't look good.
1) The text is too large and wraps
2) It includes all the extraneous spaces in the string

There is an error in the code component. the props variable does not exist

**Comment by mudrz** [comment]
fixed the props, though
I haven't included code highlighting and ESLint catches such typos

**Comment by chad-autry** [comment]
Merged, but next time I'm going to enforce smaller PRs focusing on a single issue at a time.
I also left the yarn.lock, but I'm not making any guarantee of keeping it updated myself. I'm interested in updating to npm v5 when it becomes more stable.

**Pull request merged**
